-- MySQL Script generated by MySQL Workbench
-- 05/17/17 03:27:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HospitalManagementSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HospitalManagementSystem` ;

-- -----------------------------------------------------
-- Schema HospitalManagementSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HospitalManagementSystem` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `HospitalManagementSystem` ;

-- -----------------------------------------------------
-- Table `HospitalManagementSystem`.`employeeregistration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HospitalManagementSystem`.`employeeregistration` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HospitalManagementSystem`.`employeeregistration` (
  `EmployeeID` VARCHAR(20) NOT NULL,
  `Username` VARCHAR(30) NOT NULL,
  `Password_1` VARCHAR(30) NOT NULL,
  `Password_2` VARCHAR(30) NOT NULL,
  `Full_Name` VARCHAR(60) NOT NULL,
  `NIC_Number` VARCHAR(10) NULL,
  `Gender` VARCHAR(10) NOT NULL,
  `Position` VARCHAR(30) NOT NULL,
  `Age` INT NOT NULL,
  `DOB` DATE NOT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `City` VARCHAR(30) NOT NULL,
  `Phone_Number` INT NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Details` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HospitalManagementSystem`.`patientregistration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HospitalManagementSystem`.`patientregistration` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HospitalManagementSystem`.`patientregistration` (
  `PatientID` VARCHAR(10) NOT NULL,
  `FullName` VARCHAR(80) NOT NULL,
  `NICNumber` VARCHAR(10) NULL,
  `Gender` VARCHAR(10) NOT NULL,
  `Occupation` VARCHAR(30) NOT NULL,
  `Age` INT NOT NULL,
  `DOB` DATE NOT NULL,
  `Address` VARCHAR(80) NOT NULL,
  `City` VARCHAR(30) NOT NULL,
  `PhoneNumber` INT NOT NULL,
  `Ward` VARCHAR(15) NOT NULL,
  `AssingDocotor` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(40) NULL,
  `Details` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`PatientID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HospitalManagementSystem`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HospitalManagementSystem`.`attendance` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HospitalManagementSystem`.`attendance` (
  `EmployeeID` VARCHAR(10) NOT NULL,
  `Date` DATE NOT NULL,
  `Attendance` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`EmployeeID`, `Date`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HospitalManagementSystem`.`paiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HospitalManagementSystem`.`paiment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HospitalManagementSystem`.`paiment` (
  `PaimentID` VARCHAR(10) NOT NULL,
  `PatientID` VARCHAR(10) NOT NULL,
  `DateAndTime` DATETIME NOT NULL,
  `Ammount` FLOAT NOT NULL,
  `EmployeeID` VARCHAR(10) NOT NULL,
  `PaimentName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PaimentID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `PaymentKey_idx` ON `HospitalManagementSystem`.`paiment` (`EmployeeID` ASC);

SHOW WARNINGS;
CREATE INDEX `Payment_idx` ON `HospitalManagementSystem`.`paiment` (`PatientID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HospitalManagementSystem`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HospitalManagementSystem`.`salary` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HospitalManagementSystem`.`salary` (
  `EmployeeID` VARCHAR(10) NOT NULL,
  `Year` INT NOT NULL,
  `Month` VARCHAR(15) NOT NULL,
  `Balance` FLOAT NULL,
  PRIMARY KEY (`EmployeeID`, `Year`, `Month`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HospitalManagementSystem`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HospitalManagementSystem`.`test` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HospitalManagementSystem`.`test` (
  `TestID` VARCHAR(10) NOT NULL,
  `PatientID` VARCHAR(10) NOT NULL,
  `TestName` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`TestID`, `PatientID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Test_idx` ON `HospitalManagementSystem`.`test` (`PatientID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `HospitalManagementSystem`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HospitalManagementSystem`.`treatment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `HospitalManagementSystem`.`treatment` (
  `TreatmentID` VARCHAR(10) NOT NULL,
  `PatientID` VARCHAR(10) NOT NULL,
  `TreatmentNmae` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`TreatmentID`, `PatientID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Treat_idx` ON `HospitalManagementSystem`.`treatment` (`PatientID` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
