/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class EmployeeRegistration extends javax.swing.JFrame {

    /**
     * Creates new form MemberRegistratin
     */
    public EmployeeRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmployeeRegistrationUsername = new javax.swing.JTextField();
        txtEmployeeRegistrationPassword_1 = new javax.swing.JTextField();
        txtEmployeeRegistrationPassword_2 = new javax.swing.JTextField();
        txtEmployeeRegistrationFullName = new javax.swing.JTextField();
        ComboBoxtxtEmployeeRegistrationGender = new javax.swing.JComboBox<>();
        txtEmployeeRegistrationAge = new javax.swing.JTextField();
        txtEmployeeRegistrationAddress = new javax.swing.JTextField();
        txtEmployeeRegistrationCity = new javax.swing.JTextField();
        txtEmployeeRegistrationPhoneNumber = new javax.swing.JTextField();
        txtEmployeeRegistrationEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEmployeeRegistrationDetails = new javax.swing.JTextArea();
        btnEmployeeRegistrationRegister = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnEmployeeRegistrationBack = new javax.swing.JButton();
        btnEmployeeRegistrationClear = new javax.swing.JButton();
        ComboBoxtxtEmployeeRegistrationPosition = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtEmployeeRegistrationNIC = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtEmployeeRegistrationFormatDOB = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtEmployeeRegistrationEmployeeID = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtLoginUsername1 = new javax.swing.JTextField();
        txtLoginPassword1 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnLoginEnter = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Managemenet System");
        setFont(new java.awt.Font("a_Dodger", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(14, 121, 226));

        jLabel1.setText("Employee Registration");

        jLabel2.setText("Username :");

        jLabel3.setText("Password :");

        jLabel4.setText("Password :");

        jLabel5.setText("Full Name :");

        jLabel6.setText("Gender :");

        jLabel7.setText("Position");

        jLabel8.setText("Age :");

        jLabel9.setText("Address :");

        jLabel10.setText("City :");

        jLabel11.setText("Phone Number :");

        jLabel12.setText("E-mail :");

        jLabel13.setText("Details :");

        ComboBoxtxtEmployeeRegistrationGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        ComboBoxtxtEmployeeRegistrationGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxtxtEmployeeRegistrationGenderActionPerformed(evt);
            }
        });

        txtEmployeeRegistrationAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmployeeRegistrationAgeKeyTyped(evt);
            }
        });

        txtEmployeeRegistrationPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmployeeRegistrationPhoneNumberKeyTyped(evt);
            }
        });

        txtEmployeeRegistrationDetails.setColumns(20);
        txtEmployeeRegistrationDetails.setRows(5);
        jScrollPane1.setViewportView(txtEmployeeRegistrationDetails);

        btnEmployeeRegistrationRegister.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmployeeRegistrationRegister.setText("Register");
        btnEmployeeRegistrationRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRegistrationRegisterActionPerformed(evt);
            }
        });

        jLabel14.setText("*");

        jLabel15.setText("*");

        jLabel16.setText("*");

        jLabel17.setText("*");

        jLabel18.setText("*");

        jLabel19.setText("*");

        btnEmployeeRegistrationBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmployeeRegistrationBack.setText("Back");
        btnEmployeeRegistrationBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRegistrationBackActionPerformed(evt);
            }
        });

        btnEmployeeRegistrationClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmployeeRegistrationClear.setText("Clear");

        ComboBoxtxtEmployeeRegistrationPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse", "Maintenance staff" }));

        jLabel25.setText("*  =  Required Fileds");

        jLabel26.setText("NIC Number :");

        txtEmployeeRegistrationNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmployeeRegistrationNICKeyTyped(evt);
            }
        });

        jLabel27.setText("DOB :");

        jLabel28.setText("*");

        jLabel29.setText("Employee ID :");

        jLabel30.setText("*");

        jPanel2.setBackground(new java.awt.Color(8, 75, 193));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jLabel24.setText("Are You Employee..?");

        jLabel23.setText("Login");

        jLabel21.setText("Usename :");

        jLabel22.setText("Password :");

        btnLoginEnter.setText("Enter");
        btnLoginEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtLoginUsername1)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(32, 32, 32))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtLoginPassword1)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLoginEnter)
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(30, 30, 30)
                .addComponent(btnLoginEnter)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/images (1).png"))); // NOI18N

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/images.png"))); // NOI18N

        jLabel32.setText("(YY/ MM/ DD)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel26)
                            .addComponent(jLabel29)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEmployeeRegistrationBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEmployeeRegistrationClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEmployeeRegistrationRegister)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ComboBoxtxtEmployeeRegistrationGender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmployeeRegistrationCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEmployeeRegistrationAge, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEmployeeRegistrationFormatDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmployeeRegistrationEmployeeID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeRegistrationAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxtxtEmployeeRegistrationPosition, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmployeeRegistrationUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeRegistrationPassword_1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeRegistrationPassword_2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeRegistrationFullName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeRegistrationNIC, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeRegistrationEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeRegistrationPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel28))
                                        .addGap(171, 171, 171)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel32))
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel31)))))))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(txtEmployeeRegistrationUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(txtEmployeeRegistrationPassword_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel15))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtEmployeeRegistrationPassword_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel29)
                                                .addComponent(txtEmployeeRegistrationEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel30))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtEmployeeRegistrationFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeRegistrationNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxtxtEmployeeRegistrationGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(ComboBoxtxtEmployeeRegistrationPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmployeeRegistrationAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel27)
                                    .addComponent(txtEmployeeRegistrationFormatDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel32)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeRegistrationAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeRegistrationCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeRegistrationPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmployeeRegistrationEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(13, 13, 13))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(btnEmployeeRegistrationBack)
                    .addComponent(btnEmployeeRegistrationClear)
                    .addComponent(btnEmployeeRegistrationRegister))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeRegistrationBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRegistrationBackActionPerformed
        LoginFrame loginframe = new LoginFrame();
        loginframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeRegistrationBackActionPerformed

    private void btnEmployeeRegistrationRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRegistrationRegisterActionPerformed
        try {
            if(txtEmployeeRegistrationEmployeeID.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Employee ID");
        }else if(txtEmployeeRegistrationUsername.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Username");
        }else if(txtEmployeeRegistrationFullName.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Full Name");
        }else if(txtEmployeeRegistrationNIC.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up NIC Number");
        }else if(txtEmployeeRegistrationAge.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up Age");
        }else if(txtEmployeeRegistrationFormatDOB.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up DOB");
        }else if(txtEmployeeRegistrationPassword_1.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up 1st Password");
        }else if(txtEmployeeRegistrationPassword_2.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up 2nd Password");
        }
            
            
            else{
             Statement stat = DataBaseHospitalMS.getStatement();
            stat.executeUpdate("INSERT INTO employeeregistration(EmployeeID,Username,Password_1,Password_2,Full_Name,NIC_Number,Gender,Position,Age,DOB,Address,City,Phone_Number,Email,Details) VALUES ('"+txtEmployeeRegistrationEmployeeID.getText()+"','"+txtEmployeeRegistrationUsername.getText()+"','"+txtEmployeeRegistrationPassword_1.getText()+"','"+txtEmployeeRegistrationPassword_2.getText()+"','"+txtEmployeeRegistrationFullName.getText()+"','"+txtEmployeeRegistrationNIC.getText()+"','"+ComboBoxtxtEmployeeRegistrationGender.getSelectedItem()+"','"+ComboBoxtxtEmployeeRegistrationPosition.getSelectedItem()+"','"+txtEmployeeRegistrationAge.getText()+"','"+txtEmployeeRegistrationFormatDOB.getText()+"','"+txtEmployeeRegistrationAddress.getText()+"','"+txtEmployeeRegistrationCity.getText()+"','"+txtEmployeeRegistrationPhoneNumber.getText()+"','"+txtEmployeeRegistrationEmail.getText()+"','"+txtEmployeeRegistrationDetails.getText()+"')");
           JOptionPane.showMessageDialog(null, "Successfull..!"); 
            }
           
              
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnEmployeeRegistrationRegisterActionPerformed

    private void ComboBoxtxtEmployeeRegistrationGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxtxtEmployeeRegistrationGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxtxtEmployeeRegistrationGenderActionPerformed

    private void btnLoginEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginEnterActionPerformed
        if(txtLoginUsername1.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else if(txtLoginPassword1.getPassword().length==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else{
            String user = txtLoginUsername1.getText();   // Collecting the input
            char[] pass = txtLoginPassword1.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if(validate_login(user,pwd)){
                JOptionPane.showMessageDialog(null, "Correct Login Credentials"); 
                Home home = new Home();
                home.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect Login Credentials","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnLoginEnterActionPerformed

    private void txtEmployeeRegistrationAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeRegistrationAgeKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }else{
        if(txtEmployeeRegistrationAge.getText().length()==10){
            evt.consume();
        }
        }
    }//GEN-LAST:event_txtEmployeeRegistrationAgeKeyTyped

    private void txtEmployeeRegistrationNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeRegistrationNICKeyTyped
        if(txtEmployeeRegistrationNIC.getText().length()==10){
        evt.consume();
        }
    }//GEN-LAST:event_txtEmployeeRegistrationNICKeyTyped

    private void txtEmployeeRegistrationPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeRegistrationPhoneNumberKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a)){
            evt.consume();
        }else{
        if(txtEmployeeRegistrationPhoneNumber.getText().length()==10){
            evt.consume();
        }
        }
    }//GEN-LAST:event_txtEmployeeRegistrationPhoneNumberKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxtxtEmployeeRegistrationGender;
    private javax.swing.JComboBox<String> ComboBoxtxtEmployeeRegistrationPosition;
    private javax.swing.JButton btnEmployeeRegistrationBack;
    private javax.swing.JButton btnEmployeeRegistrationClear;
    private javax.swing.JButton btnEmployeeRegistrationRegister;
    private javax.swing.JButton btnLoginEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmployeeRegistrationAddress;
    private javax.swing.JTextField txtEmployeeRegistrationAge;
    private javax.swing.JTextField txtEmployeeRegistrationCity;
    private javax.swing.JTextArea txtEmployeeRegistrationDetails;
    private javax.swing.JTextField txtEmployeeRegistrationEmail;
    private javax.swing.JTextField txtEmployeeRegistrationEmployeeID;
    private javax.swing.JFormattedTextField txtEmployeeRegistrationFormatDOB;
    private javax.swing.JTextField txtEmployeeRegistrationFullName;
    private javax.swing.JTextField txtEmployeeRegistrationNIC;
    private javax.swing.JTextField txtEmployeeRegistrationPassword_1;
    private javax.swing.JTextField txtEmployeeRegistrationPassword_2;
    private javax.swing.JTextField txtEmployeeRegistrationPhoneNumber;
    private javax.swing.JTextField txtEmployeeRegistrationUsername;
    private javax.swing.JPasswordField txtLoginPassword1;
    private javax.swing.JTextField txtLoginUsername1;
    // End of variables declaration//GEN-END:variables

    private boolean validate_login(String user, String pwd) {
        try {
            
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitalmanagementsystem?" + "user=root&password=");     
       PreparedStatement pst = conn.prepareStatement("Select * from employeeregistration where Username=? and Password_1=?");
       pst.setString(1, user); 
       pst.setString(2, pwd);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;
            
            
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}


